--2019 yýlýnda yapýlan alým ve satýþlardan elde edilen karý bul 
SELECT SUM(SALE_PRICE) AS TOPLAMSATIS, 
SUM(PURCH_PRICE) AS TOPLAMALINAN,SUM(SALE_PRICE)-SUM(PURCH_PRICE) AS KAR 
FROM SALE_,PURCHASE_  WHERE DATEPART(YEAR FROM SALE_DATE) = 2019  AND DATEPART(YEAR FROM PURCH_DATE ) = 2019 